# Generated by Django 4.2 on 2023-04-28 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_loaimon_maloai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goimon',
            name='giatien',
        ),
        migrations.RemoveField(
            model_name='goimon',
            name='mamon',
        ),
        migrations.RemoveField(
            model_name='goimon',
            name='tenmon',
        ),
        migrations.CreateModel(
            name='ctgoimon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluong', models.IntegerField()),
                ('mon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.thucdon')),
            ],
        ),
        migrations.AddField(
            model_name='goimon',
            name='ctgoimon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ctgoimon'),
        ),
    ]
