# Generated by Django 4.2 on 2023-04-28 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_goimon_thanhtien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goimon',
            name='ctgoimon',
        ),
        migrations.AddField(
            model_name='ctgoimon',
            name='goimon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.goimon'),
        ),
    ]
