# Generated by Django 4.2 on 2023-04-28 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_goimon_thoigiangoi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taikhoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matkhau', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thongtin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manguoidung', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('sdt', models.CharField(max_length=50, null=True)),
                ('hoten', models.CharField(max_length=50, null=True)),
                ('diachi', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='thucdon',
            name='mamon',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='taikhoan',
            name='Thongtin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.thongtin'),
        ),
    ]
