# Generated by Django 4.2 on 2023-04-28 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_taikhoan_nguoidung_nhanvien'),
    ]

    operations = [
        migrations.CreateModel(
            name='Khohang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manvl', models.CharField(max_length=50, null=True)),
                ('tennvl', models.CharField(max_length=50, null=True)),
                ('mota', models.CharField(max_length=50, null=True)),
                ('dvt', models.CharField(max_length=50, null=True)),
                ('soluong', models.CharField(max_length=50, null=True)),
                ('giatien', models.FloatField()),
                ('manguoidung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.thongtin')),
            ],
        ),
        migrations.RenameField(
            model_name='nhanvien',
            old_name='email',
            new_name='manhanvien',
        ),
        migrations.AddField(
            model_name='goimon',
            name='giatien',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='goimon',
            name='mon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.thucdon'),
        ),
        migrations.AddField(
            model_name='goimon',
            name='soluong',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loaimon',
            name='manguoidung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.thongtin'),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='mucluong',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='namsinh',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='thucdon',
            name='manguoidung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.thongtin'),
        ),
        migrations.AlterField(
            model_name='thucdon',
            name='maloai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.loaimon'),
        ),
        migrations.DeleteModel(
            name='ctgoimon',
        ),
    ]
