# Generated by Django 4.2 on 2023-04-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_goimon_giatien_goimon_manguoidung_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nguoidung',
            name='Thongtin',
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='manguoidung',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='taikhoan',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='thongtin',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
