# Generated by Django 4.2 on 2023-04-29 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_nguoidung_phien'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nguoidung',
            old_name='phien',
            new_name='session',
        ),
    ]
