# Generated by Django 4.2 on 2023-04-29 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_phien_nguoidung_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nguoidung',
            name='session',
        ),
    ]
