# Generated by Django 4.2 on 2023-04-30 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('app', '0021_alter_nguoidung_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='thongtin',
            name='matkhau',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='thongtin',
            name='session',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
        migrations.AddField(
            model_name='thongtin',
            name='taikhoan',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Nguoidung',
        ),
    ]
