# Generated by Django 4.2 on 2023-04-30 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('app', '0022_thongtin_matkhau_thongtin_session_thongtin_taikhoan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thongtin',
            name='matkhau',
        ),
        migrations.RemoveField(
            model_name='thongtin',
            name='session',
        ),
        migrations.RemoveField(
            model_name='thongtin',
            name='taikhoan',
        ),
        migrations.CreateModel(
            name='Nguoidung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manguoidung', models.CharField(max_length=50, null=True)),
                ('taikhoan', models.EmailField(max_length=50, null=True)),
                ('matkhau', models.CharField(max_length=50, null=True)),
                ('session', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
            ],
        ),
    ]
