# Generated by Django 4.2 on 2023-04-30 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('app', '0023_remove_thongtin_matkhau_remove_thongtin_session_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nguoidung',
            old_name='matkhau',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='nguoidung',
            old_name='taikhoan',
            new_name='username',
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
    ]
