# Generated by Django 4.2 on 2023-04-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_matkhau_nguoidung_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nguoidung',
            old_name='username',
            new_name='taikhoan',
        ),
        migrations.RemoveField(
            model_name='nguoidung',
            name='password',
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='matkhau',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
