# Generated by Django 4.2 on 2023-04-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_nguoidung_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nguoidung',
            old_name='taikhoan',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='nguoidung',
            old_name='matkhau',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='nguoidung',
            name='session',
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
