# Generated by Django 4.2 on 2023-04-30 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_taikhoan_nguoidung_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nguoidung',
            old_name='password',
            new_name='matkhau',
        ),
        migrations.RenameField(
            model_name='nguoidung',
            old_name='email',
            new_name='taikhoan',
        ),
        migrations.RemoveField(
            model_name='nguoidung',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='nguoidung',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='nguoidung',
            name='last_login',
        ),
    ]
