# Generated by Django 4.2 on 2023-04-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_rename_password_nguoidung_matkhau_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nguoidung',
            old_name='taikhoan',
            new_name='email',
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
