# Generated by Django 4.2 on 2023-04-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_rename_taikhoan_nguoidung_email_nguoidung_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nguoidung',
            old_name='matkhau',
            new_name='password',
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
