# Generated by Django 4.2 on 2023-04-30 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_rename_matkhau_nguoidung_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nguoidung',
        ),
    ]
