# Generated by Django 4.2 on 2023-04-30 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_delete_nguoidung'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thongtin',
            old_name='manguoidung',
            new_name='tenquan',
        ),
        migrations.RemoveField(
            model_name='goimon',
            name='manguoidung',
        ),
        migrations.RemoveField(
            model_name='khohang',
            name='manguoidung',
        ),
        migrations.RemoveField(
            model_name='loaimon',
            name='manguoidung',
        ),
        migrations.RemoveField(
            model_name='nhanvien',
            name='manguoidung',
        ),
        migrations.RemoveField(
            model_name='thucdon',
            name='manguoidung',
        ),
    ]
