# Generated by Django 4.2 on 2023-05-01 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
