# Generated by Django 4.2 on 2023-05-02 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
