# Generated by Django 4.2 on 2023-05-02 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0039_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CusUser',
        ),
    ]
