# Generated by Django 4.2 on 2023-05-02 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_rename_user_cususer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CusUser',
        ),
    ]
