# Generated by Django 4.2 on 2023-05-02 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_cususer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CusUser',
        ),
    ]
