# Generated by Django 4.2 on 2023-05-02 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_delete_thongtin_alter_myuser_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
