# Generated by Django 4.2 on 2023-05-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_thongtin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thongtin',
            old_name='manhanvien',
            new_name='tenquan',
        ),
        migrations.AddField(
            model_name='thongtin',
            name='diachi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='thongtin',
            name='sdt',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
