# Generated by Django 4.2 on 2023-05-03 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0048_rename_manhanvien_thongtin_tenquan_thongtin_diachi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaimon',
            name='maloai',
        ),
        migrations.RemoveField(
            model_name='thucdon',
            name='maloai',
        ),
        migrations.RemoveField(
            model_name='thucdon',
            name='mamon',
        ),
        migrations.AddField(
            model_name='loaimon',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thucdon',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thucdon',
            name='anh',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='thucdon',
            name='giatien',
            field=models.FloatField(null=True),
        ),
    ]
