# Generated by Django 4.2 on 2023-05-04 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_thucdon_loaimon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thucdon',
            name='Loaimon',
        ),
        migrations.RemoveField(
            model_name='thucdon',
            name='anh',
        ),
        migrations.RemoveField(
            model_name='thucdon',
            name='nguyenlieu',
        ),
    ]
