# Generated by Django 4.2 on 2023-05-04 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_remove_thucdon_loaimon_remove_thucdon_anh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thucdon',
            name='Loaimon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.loaimon'),
        ),
    ]
