# Generated by Django 4.2 on 2023-05-04 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_thucdon_loaimon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thucdon',
            old_name='Loaimon',
            new_name='loaimon',
        ),
    ]
