# Generated by Django 4.2 on 2023-05-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_rename_loaimon_thucdon_loaimon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thucdon',
            name='loaimon',
        ),
    ]
