# Generated by Django 4.2 on 2023-05-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_thucdon_loaimon'),
    ]

    operations = [
        migrations.AddField(
            model_name='thucdon',
            name='anh',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
