# Generated by Django 4.2 on 2023-05-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_alter_thucdon_anh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thucdon',
            name='anh',
            field=models.ImageField(null=True, upload_to='app/static/img/'),
        ),
    ]
