# Generated by Django 4.2 on 2023-05-06 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0060_alter_thucdon_anh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khohang',
            name='manvl',
        ),
        migrations.AddField(
            model_name='khohang',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='khohang',
            name='soluong',
            field=models.IntegerField(null=True),
        ),
    ]
