# Generated by Django 4.2 on 2023-05-08 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0061_remove_khohang_manvl_khohang_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhanvien',
            name='manhanvien',
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='giocong',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='luong',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='mucluong',
            field=models.FloatField(null=True),
        ),
    ]
