# Generated by Django 4.2 on 2023-05-10 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0063_goimon_user_alter_goimon_mon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goimon',
            name='thoigiangoi',
        ),
        migrations.AlterField(
            model_name='goimon',
            name='soluong',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Donhang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoigiantao', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CtDonhang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluong', models.IntegerField(null=True)),
                ('donhang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.donhang')),
                ('mon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.thucdon')),
            ],
        ),
    ]
