# Generated by Django 4.2 on 2023-05-10 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0064_remove_goimon_thoigiangoi_alter_goimon_soluong_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctdonhang',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
