# Generated by Django 4.2 on 2023-05-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_ctdonhang_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='thanhtien',
            field=models.FloatField(null=True),
        ),
    ]
