# Generated by Django 4.2 on 2023-05-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_donhang_thanhtien'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='loai',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
