# Generated by Django 4.2 on 2023-05-10 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0067_donhang_loai'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvien',
            name='danglam',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Calamviec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaoca', models.DateTimeField(auto_now_add=True)),
                ('nhanvien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.nhanvien')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
