# Generated by Django 4.2 on 2023-05-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_nhanvien_danglam_calamviec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='giocong',
            field=models.FloatField(null=True),
        ),
    ]
