# Generated by Django 4.2 on 2023-05-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_alter_nhanvien_giocong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calamviec',
            name='vaoca',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='giocong',
            field=models.FloatField(default=0, null=True),
        ),
    ]
