# Generated by Django 4.2 on 2023-05-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_alter_calamviec_vaoca_alter_nhanvien_giocong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='giocong',
            field=models.FloatField(null=True),
        ),
    ]
