# Generated by Django 4.2 on 2023-05-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_thongtinkho_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='thongtinkho',
            name='kieunhap',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
