# Generated by Django 4.2 on 2023-05-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_thongtinkho_kieunhap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongtinkho',
            name='ngaynhap',
            field=models.DateTimeField(),
        ),
    ]
